### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by aejes** [felipebz/sonar-plsql#1]
Hi Felipe,

Does you have any basic compiling / installation instructions? 

Thanks

John

**Comment by felipebz** [comment]
Hi John.

Thanks for your interest.

If you have [Maven](https://maven.apache.org/download.cgi) in your PATH, you can run `mvn package` in the source folder to compile (the main *.jar file will be generated in folder sonar-plsql-open-plugin/target/). Or just grab the latest version [here](https://ci.appveyor.com/project/felipebz/sonar-plsql/build/artifacts).

Copy this *.jar to SONARQUBE_HOME/extensions/plugins and restart the SonarQube server. Then you can [use SonarQube Scanner to analyze code](http://docs.sonarqube.org/display/SONAR/Analyzing+with+SonarQube+Scanner).
