### ISSUE TITLE
Fix parsing errors of PL/JSON project

### ISSUE THREAD

**Issue by felipebz** [felipebz/sonar-plsql#10]
When analyzing the [PL/JSON](https://github.com/pljson/pljson) project, some parsing errors are generated.

Ths issue will be used to track this errors.
- [x] SQL*Plus commands: https://github.com/pljson/pljson/blob/be08929198b3aa12bcfecd0d67ac77af77b952e1/examples/ex1.sql#L31
- [x] fix CREATE TABLE (https://github.com/pljson/pljson/blob/be08929198b3aa12bcfecd0d67ac77af77b952e1/examples/ex13.sql#L25).
- [x] DROP TABLE (https://github.com/pljson/pljson/blob/be08929198b3aa12bcfecd0d67ac77af77b952e1/examples/ex_pljson_table.sql#L39)
- [ ] ALTER SESSION (https://github.com/pljson/pljson/blob/be08929198b3aa12bcfecd0d67ac77af77b952e1/install.sql#L8)
- [x] GOTO with label (https://github.com/pljson/pljson/blob/be08929198b3aa12bcfecd0d67ac77af77b952e1/src/addons/json_helper.sql#L272)
- [x] CREATE TYPE (https://github.com/pljson/pljson/blob/be08929198b3aa12bcfecd0d67ac77af77b952e1/src/addons/pljson_table_impl.typ#L2)
- [x] CREATE SYNONYM (https://github.com/pljson/pljson/blob/be08929198b3aa12bcfecd0d67ac77af77b952e1/src/grantsandsynonyms.sql#L3)

**Comment by svscorp** [comment]
@felipebz Is "CREATE TABLE " analysis fix is still in progress? I am using SNAPSHOT-2.0 and trying to analyze sample Oracle script, that shows parse error on PK creation (both when inside CREATE TABLE or via ALTER TABLE):

````
CREATE TABLE customers
( 
  customer_id number(10) NOT NULL,
  customer_name varchar2(50) NOT NULL,
  city varchar2(50),
  CONSTRAINT customers_pk PRIMARY KEY (customer_id)
);
````

Thank you for the plugin!

**Comment by felipebz** [comment]
Hi @svscorp. Technically, it's still "in progress", but I was more interested in parsing PL/SQL code than SQL scripts. That's why I didn't priorize it. (Or maybe I got scared by the [amount of variations](https://docs.oracle.com/database/121/SQLRF/clauses002.htm#CJAEDFIB)) ;-)

I'll fix the most common cases soon.
