### ISSUE TITLE
Can there be a grammar rule that will identify the new line?

### ISSUE THREAD

**Issue by HaroonRaizada** [felipebz/sonar-plsql#100]
I have a requirement like, i have to ensure that sql code is properly intended. I have to check if there is a new line in the statement or not. Is there any way to achieve that?

**Comment by felipebz** [comment]
Hi.

You could write a custom rule checking the `node.getToken().getLine()` and `node.getToken().getColumn()` of the AstNode instance, compare them and you'll know if the code is indented. But depending what exactly you want to do, this will become very complicated...
