### ISSUE TITLE
Access to analysed file object

### ISSUE THREAD

**Issue by khirzer** [felipebz/sonar-plsql#101]
Hi,

I've implemented a custom rule where I retrieve some file attributes. To get the file object I used the code

    File file = this.getContext().plSqlFile().inputFile().file();

With https://github.com/felipebz/sonar-plsql/commit/4849859ff437dbb648d9eb98cf6f526a6510cb4f 'inputFile' was removed in class 'PlSqlFile'. Is there another way to get the file object?

Thanks!
Karl

**Comment by felipebz** [comment]
Hi @khirzer. I've reverted that commit. ;-)
