### ISSUE TITLE
The rule repository plsql must not be defined for two languages plsql and plsqlopen.

### ISSUE THREAD

**Issue by HaroonRaizada** [felipebz/sonar-plsql#103]
Hi,

We are getting IllegalStateException with error"The rule repository plsql must not be defined for two languages plsql and plsqlopen." This is coming as Sonar's licensed plugin is also available in SOnarQube Project.

If we rename the buil in profile from "Sonar Way" to "Sonar Way2", will that change will resolve our issue?As for two different profiles we can have two different languages?

**Comment by felipebz** [comment]
Hi @HaroonRaizada.

I've made some changes and now I can load the plugin side-by-side with SonarPLSQL. I tested with SonarQube 7.6 Developer Edition.

![image](https://user-images.githubusercontent.com/13829/53307055-02bf5980-3873-11e9-8b03-511b0df394c2.png)

But I can't confirm if the sonar-scanner will execute without any errors...
