### ISSUE TITLE
False positive for rule 'NotASelectedExpression'

### ISSUE THREAD

**Issue by khirzer** [felipebz/sonar-plsql#104]
Hi!

I've noticed that the following query creates an issue (rule 'NotASelectedExpression') although the exception ORA-01791 is not thrown in this case:

    select distinct(field)
      from table
     order by substr(field, 2);

Can you check that please?

Thanks!
Karl

**Comment by felipebz** [comment]
Hi @khirzer. I'd forgot about this false positive. :sweat_smile: (this is why this rule isn't enabled by default)

https://github.com/felipebz/sonar-plsql/blob/37d8178e992c631873b98d5156484897fdfa5107/plsql-checks/src/test/resources/checks/not_a_selected_expression.sql#L11-L21

I've just fixed theses false positives. Thanks for bringing this up!
