### ISSUE TITLE
Query for customization

### ISSUE THREAD

**Issue by kbhuvanamohan** [felipebz/sonar-plsql#105]
Hi Felipe,

I was wondering if we have any option to use XPath to customize this plugin to add new rules.

Thanks!

**Comment by felipebz** [comment]
Hi.

Yes, you can create a rule using XPath. The steps are the same as described in the [SonarQube documentation](https://docs.sonarqube.org/display/DEV/Adding+Coding+Rules+using+XPath).

You can download the toolkit from here: https://github.com/felipebz/sonar-plsql/releases/download/2.2.0/sslr-plsql-toolkit-2.2.0.jar

Add your code, click on "Parse Source Code" and you'll see the structure generated by the parser. You can test a XPath expression there:

![image](https://user-images.githubusercontent.com/13829/54478304-617f4f80-47ef-11e9-9be1-87ab83373152.png)

In the SonarQube server, find the rule "Track breaches of an XPath rule":

![image](https://user-images.githubusercontent.com/13829/54478332-a86d4500-47ef-11e9-8302-3f1be60e47e6.png)

Then create a custom rule using your XPath expression:

![image](https://user-images.githubusercontent.com/13829/54478362-0dc13600-47f0-11e9-9b89-b9c8ea4d5fee.png)
