### ISSUE TITLE
Analysis stuck

### ISSUE THREAD

**Issue by felipebz** [felipebz/sonar-plsql#12]
@nmorais on https://github.com/felipebz/sonar-plsql/issues/8#issuecomment-251512705:

> @felipebz,  I got a problem after commit: _Complete LIKE syntax_  2d77364
> 
> The plugin got stuck at a file until the build timed out (30 minutes).
> 
> Do you have any tips on how to troubleshoot this kind of problem?

**Comment by felipebz** [comment]
@nmorais do you already know what file is causing the problem in the analysis, right?

Could you open the problematic file in the [sslr-plsql-toolkit](https://ci.appveyor.com/api/buildjobs/r1f2w4k1e7dkthjm/artifacts/sslr-plsql-toolkit%2Ftarget%2Fsslr-plsql-toolkit-1.0-SNAPSHOT-sources.jar) and parse it, please?

If I broke the parser, the sslr-plsql-tookit will get stuck too.

**Comment by nmorais** [comment]
@felipebz,   sslr-plsql-toolkit got stuck too.

I have found what was freezing it in the file. After cutting several parts of the file, i have found that a subquery inside an EXISTS clause was the problem.

In previous commits, the parser simply failed because a _AT_ as table alias. I dont know how the parser does not failed again, but moving the AT keyword to non reserved solved the problem.

As I have thousands of ATs used as table alias in my code, I have to support it anyway. 

Finally, as it is supported, I'm making pull request  to move it to non reserved.

**Comment by felipebz** [comment]
@nmorais just to be clear, the cause of the freezing is the use "AT" as a table alias? Or the problem with the subquery inside an EXISTS clause that you mentioned is another situation?

Anyway, you made me realize that I made a wrong assumption in the PlSqlKeyword class.

Actually there are two sets of reserved keywords:
- PL/SQL Reserved Words: https://docs.oracle.com/database/121/LNPLS/reservewords.htm
- SQL Reserved Words: https://docs.oracle.com/database/121/SQLRF/ap_keywd001.htm

"AT" is a reserved keyword in PL/SQL (we can't declare a "PROCEDURE AT(...)"), but it isn't reserved in SQL. Thanks for the pull request, I'll review it soon.

**Comment by nmorais** [comment]
@felipebz, I have found that the cause was the AT keyword itself. This file has 1k+ lines and the keyword appears dozens of times. Parsing runned instantly after replacing the AT keyword for other alias.

**Comment by nmorais** [comment]
Hi @felipebz, 
  
    I think this issue can be closed.

    This problem surfaced again in the same file last week. It was related to a issue in  a CASE statement. When the implementation the the CASE statement was fixed, the filed parsed fast.

    It seems a problem that can appear when parser fails in complex files, not a bug of this plugin.

    Since 98% of my code base is parsing successfully, I hope this problem never appear again! :)

**Comment by felipebz** [comment]
Since it can't be reproduced anymore, I will close this issue. ;-)
