### ISSUE TITLE
Parse error at line

### ISSUE THREAD

**Issue by CRACKISH** [felipebz/sonar-plsql#23]
I have many errors like:
![image](https://cloud.githubusercontent.com/assets/25606280/25039931/0eea4a62-210f-11e7-8144-f9ad4c0587b9.png)

**Comment by felipebz** [comment]
Hi.

Are you sure this code is correct and compiles without any errors? It should have an "IS" or "AS" after the procedure name. This plugin can't parse files with syntax errors.

I tried to compile this code:

```
CREATE OR REPLACE PROCEDURE "tsp_DisableSendResolutionProc"
BEGIN
  NULL;
END;
/
```

In Oracle 10gR2, 11gR2 and 12cR2 I get an error similar to:
```
PLS-00103: Encountered the symbol "BEGIN" when expecting one of the following:       
( ; is with authid as cluster compress order using compiled
wrapped external deterministic parallel_enable pipelined
The symbol "is" was substituted for "BEGIN" to continue.
```

**Comment by CRACKISH** [comment]
Yes, you are right. But this should not be a parse error, this should be as sonar analysis bug.

**Comment by CRACKISH** [comment]
I have new parse error

![image](https://cloud.githubusercontent.com/assets/25606280/25121506/990d29f8-242a-11e7-87ea-6053e6b29e87.png)

**Comment by CRACKISH** [comment]
![image](https://cloud.githubusercontent.com/assets/25606280/25129668/a5ad4004-2447-11e7-8ad4-71f52ec5e1fa.png)
