### ISSUE TITLE
Add support for 'any' Syntax

### ISSUE THREAD

**Issue by phermsdorf** [felipebz/sonar-plsql#32]
possible Test in WhereClauseTest.java

```
    @Test
    public void matchesAny() {
    	assertThat(p).matches("where data = any (select 1,2,3 from dual)");
    }

```
I guess it should be some kind of new Expression in PlSqlGrammar.java but I was not able to figure it out myself ...

**Comment by felipebz** [comment]
Hi Peter.

That part of the syntax is currently parsed as a COMPARISON_EXPRESSION:

![image](https://user-images.githubusercontent.com/13829/32738990-c2c5893e-c885-11e7-8b68-1aa68cb9ece9.png)

The COMPARISON_EXPRESSION is defined as a ConditionsGrammar.CONDITION or a CONCATENATION_EXPRESSION:

https://github.com/felipebz/sonar-plsql/blob/1f9596491a312b22f59a6d5539557aef51810891/plsql-frontend/src/main/java/org/sonar/plugins/plsqlopen/api/PlSqlGrammar.java#L605-L607

So, take a look at [ConditionsGrammar class](https://github.com/felipebz/sonar-plsql/blob/9cc928e43e73517d73b8185904ee2b1f229e90ad/plsql-frontend/src/main/java/org/sonar/plugins/plsqlopen/api/ConditionsGrammar.java). The relational operators, LIKE operator, BETWEEN operator and multiset conditions are all there.

I think the RELATIONAL_OPERATOR rule should be changed to include something like `b.optional(b.firstOf(ANY, SOME, ALL))`.

Do you wanna submit a pull request?

**Comment by phermsdorf** [comment]
I'll try. Thanks for the tips.

Felipe Zorzo <notifications@github.com> schrieb am Mo., 13. Nov. 2017,
18:22:
