### ISSUE TITLE
add support for $$PLSQL_UNIT literal

### ISSUE THREAD

**Issue by phermsdorf** [felipebz/sonar-plsql#39]
That is kind of a pre-processor macro which replaces the placeholder with the plsql filename. 

See here https://livesql.oracle.com/apex/livesql/file/content_C1WQP69V5QL547I8EERSEVE81.html for documentation.

I would have added it myself but i haven't found a good starting point...

**Comment by felipebz** [comment]
Just for sake of completeness, the documentation calls this ["inquiry directives"](https://docs.oracle.com/database/121/LNPLS/fundamentals.htm#GUID-E918087C-D5A8-4CEE-841B-5333DE6D4C15) ;-)

**Comment by phermsdorf** [comment]
Thanks! Learned again ;)
