### ISSUE TITLE
Custom rules: Two issues for one item

### ISSUE THREAD

**Issue by khirzer** [felipebz/sonar-plsql#42]
Hi,

First of all: Thank you for this great work! 

I've created a plugin with custom rules according to your Wiki page. My plugin is almost identical with the template project (I only changed the table name 'user' -> 'user_objects'). Unfortunately there are two issues displayed for one item: 

![custom](https://user-images.githubusercontent.com/34029643/33267367-7e9f4908-d379-11e7-8e0d-dc953dae4d63.jpg)

I'm using SonarQube 6.5.

How can I resolve this issue? Thank you!

**Comment by felipebz** [comment]
Actually you found a bug in the demo. :-) SonarQube was registering the checks twice.

I've fixed it in https://github.com/felipebz/sonar-plsql/commit/f542b4f6cf366bc57c7a9f51358d61cd7d5914a0 separating the old PlSqlCustomRulesPlugin class in two: [PlSqlCustomRulesDefinition](https://github.com/felipebz/sonar-plsql/blob/f542b4f6cf366bc57c7a9f51358d61cd7d5914a0/plsql-custom-rules/src/main/java/com/company/plsql/PlSqlCustomRulesDefinition.java) and [PlSqlCustomRulesPlugin](https://github.com/felipebz/sonar-plsql/blob/master/plsql-custom-rules/src/main/java/com/company/plsql/PlSqlCustomRulesPlugin.java)

**Comment by khirzer** [comment]
Thank you for the quick fix! :-)
