### ISSUE TITLE
Parsing with space between relation operators

### ISSUE THREAD

**Issue by vinupriyesh** [felipebz/sonar-plsql#49]
There is this weird thing i found with relation operators.  Space inside a 'greater than equal to' operator or any double symbol relational operator is still valid and works fine with oracle. :|

For example, 
`select 'hello' from dual where 1 > = 1` is still valid and will work as a code but our parser would fail. 

I am not sure whether this has to be fixed, but sharing the info.

**Comment by felipebz** [comment]
Hi @vinupriyesh.

Yes, it's a bug. But I'm not sure how to fix this yet. I'll take a look at this soon.
