### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by alejo1889** [felipebz/sonar-plsql#50]
Hi, felipebz (thanks for the plugin)

I'm trying to use the plug-in and get parsing errors:

INFO: 3 files indexed
INFO: 0 files ignored because of inclusion/exclusion patterns
INFO: Quality profile for plsqlopen: Sonar way
INFO: Sensor PlsqlSquidSensor [plsqlopen]
INFO: 2 source files to be analyzed
ERROR: Unable to parse file: D:/RevisionPar/GEM y SALUDFAM/PLSQL_GEM/PCK_GEM_SERVICIOS.pck
ERROR: Parse error at line 6809 column 53:

 6803: 3200);
 6804:     lv_tipo_servicio CHAR;
 6805:     lv_codificacion  CHAR;
 6806:
 6807:   BEGIN
 6808:     SELECT REPLACE(RTRIM(XMLAGG(XMLELEMENT(e, prestacion, ',')
  -->                                  .EXTRACT('//text()') ORDER BY lvl DESC),
 6810:                          ','),
 6811:                    ',',
 6812:                    ',') PATH
 6813:       INTO prestaciones
 6814:       FROM (SELECT ROWNUM lvl, nmeventoreportado, prestacion
 6815:               FROM (SELECT nmeventoreportado,

INFO: 2/2 source files have been analyzed
INFO: Sensor PlsqlSquidSensor [plsqlopen] (done) | time=488ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=0ms
INFO: Sensor CPD Block Indexer
INFO: Sensor CPD Block Indexer (done) | time=16ms
INFO: No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
INFO: Calculating CPD for 1 file
INFO: CPD calculation finished
INFO: Analysis report generated in 188ms, dir size=722 KB
INFO: Analysis reports compressed in 31ms, zip size=70 KB
INFO: Analysis report uploaded in 78ms
INFO: ANALYSIS SUCCESSFUL, you can browse https: ...
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at https ...
INFO: Task total time: 1.719 s

Colud you help me, please?

**Comment by felipebz** [comment]
Hi @alejo1889.

XMLAGG with ORDER BY isn't supported yet, but it seems easy to fix... I'll fix it this soon.

Thanks!

**Comment by alejo1889** [comment]
@felipebz Thanks
