### ISSUE TITLE
Documentation for custom checks

### ISSUE THREAD

**Issue by felipebz** [felipebz/sonar-plsql#6]
The plugin has extension points to allow the creation of custom checks. This should be documented in the wiki and a sample project should be added to the source code.

**Comment by amelieq-c** [comment]
Hello,

We are trying your plugin, and we would like to add a custom rule. What should be the step-by-step ?
In advance, thank you !

Best regards,
Amélie

**Comment by felipebz** [comment]
Hi Amélie.

Sorry for the late follow up, but I've added a page explaining how to create a plugin with custom rules: https://github.com/felipebz/sonar-plsql/wiki/Create-a-plugin-with-custom-rules
