### ISSUE TITLE
Rule 'DeadCode' does not show issue - raise_application_error

### ISSUE THREAD

**Issue by khirzer** [felipebz/sonar-plsql#64]
Hi,

I've noticed that the rule 'DeadCode' does not show an issue if 'raise_application_error' is used:

    begin
      raise_application_error(-20999, 'Custom error message');
      if condition then  -- dead code
        --...
      end if;

Documentation: https://docs.oracle.com/cd/B19306_01/appdev.102/b14261/errors.htm#i3329

Would it be possible for you to add this case?

Thank you!
Karl

**Comment by felipebz** [comment]
Hi @khirzer.

Yes, it was an oversight. Thank for reporting this!
