### ISSUE TITLE
Test the official PL/SQL parser from Oracle

### ISSUE THREAD

**Issue by felipebz** [felipebz/sonar-plsql#68]
Recently Oracle released the source code of SQLcl and some components used by SQL Developer under a very permissive license, more info here: [Open Sourcing dbtools-commons, SQLcl, and more](http://krisrice.io/2018-04-12-open-sourcing-dbtools-commons-sqlcl-and-more/)

Looks like they even released the source code of their parser here: https://github.com/oracle/dbtools-commons/tree/master/common/src/main/java/oracle/dbtools/parser

We should test this parser and check if this could be used instead of our custom parser.

**Comment by felipebz** [comment]
All links are dead now, I'm not sure why.

**Comment by slachiewicz** [comment]
Actual repository cam be found here: https://github.com/oracle/oracle-db-tools

**Comment by felipebz** [comment]
Hi @slachiewicz. Actually not. The oracle-db-tools repository contains only sample code showing how to use SQLcl as a library in a project. The (now removed) dbtools-commons had the actual source code of SQLcl and some libraries shared between it and SQL Developer.

**Comment by martinmlouis** [comment]
Hi, I tried to format a file and send output to a new file and if there are no errors in the input file it is fine, but if there are some errors in the input file it just says "parser error" and no line numbers where the error happened. Not sure if this is the intended functionality. A line number and the usual oracle error message information will be good for automating SQLcl

**Comment by felipebz** [comment]
@martinmlouis sorry, but I didn't understand what you are doing. I think you are in the wrong repository...

**Comment by martinmlouis** [comment]
Hi, This is regarding SQLcl. I used it to format a SQL file hoping to get exact errors. 
format file input.sql output.sql
If there is no errors the parser silently exits successfully.
If there is an errors it just says "parser error" and does not give me the exact place where the error happened.
I am trying to validate/check_syntax for SQL files using SQLcl
Any insight on getting this done will be helpful for me,
Thanks

**Comment by felipebz** [comment]
@martinmlouis I'm afraid I can't help you... Please try to start a new thread on https://community.oracle.com/community/database/developer-tools/sql_developer/sqlcl/content

**Comment by martinmlouis** [comment]
Trying to use SyntaxError.checkSyntax class in sqlcli to check syntax 
I am trying to automate sql syntax check using sqlcli supplied jar file dbtools-common.jar in the lib dir for sqlcl-18.2.0

Sometimes it gives me this error and I am not able to figure out what this means

Expected: name_wo_function_call,identifier,name,sim_stmt,sql

Expected: name_wo_function_call,identifier,name,labeled_nonb

 

Have anyone who used SQL Developer or SQLcl for chcking syntax errors faced this issue,

Any insight would be good for me,

Thanks,
