### ISSUE TITLE
Parse error at line 1

### ISSUE THREAD

**Issue by vatasi** [felipebz/sonar-plsql#70]
Hello,

I'm not sure why but this plugin can't parse any of our SQL's. For example:

ERROR: Parse error at line 1 column 30:

  -->  CREATE OR REPLACE EDITIONABLE FUNCTION "MADMIN"."CLOB_LENGTHB" (
    2:      p_clob in clob
    3: ) return number  is
    4:      l_pos               number := 1;
    5:      l_size          number := 0;
    6: begin
    7:      while ( l_pos <= dbms_lob.getlength

Probably this is a configuration question?

**Comment by felipebz** [comment]
Hi @vatasi.

It's a bug in the parser. I used the 11g docs to implement the syntax of create function, but the "editionable function" is a 12c feature.

Thanks for reporting this, this will be fixed soon.

**Comment by vatasi** [comment]
Hi @felipebz ,

thanks a lot for the quick response. we have actually almost all types of objects EDITIONABLE - so it would be great to allow this not only for functions.
