### ISSUE TITLE
Property 'sonar.plsql.file.suffixes' is not declared as multi-values/property

### ISSUE THREAD

**Issue by vrangel** [felipebz/sonar-plsql#81]
When I run the sonar-scanner:

WARN: Property 'sonar.plsql.file.suffixes' is not declared as multi-values/property set but was read using 'getStringArray' method. The SonarQube plugin declaring this property should be updated.

**Comment by felipebz** [comment]
Hi @vrangel.

It's already fixed (https://github.com/felipebz/sonar-plsql/commit/a75e67ab139070b62ca7c79e1dccfb2b304d4757), it will be included in the next release. Thanks!

**Comment by vrangel** [comment]
Thanks for the support!
