### ISSUE TITLE
Rowtype variable marked as unused

### ISSUE THREAD

**Issue by jleendertse** [felipebz/sonar-plsql#83]
A rowtype variable being used in for loop is marked as not used. I adapted the method visitFor in SymbolVisitor:

```
    private void visitFor(AstNode node) {
        enterScope(node, null, null);
        AstNode identifier = node.getFirstChild(PlSqlKeyword.FOR).getNextSibling();
        AstNode range = node.getFirstChild(PlSqlPunctuator.RANGE);
        if (range != null) {
        	createSymbol(identifier, Symbol.Kind.VARIABLE, null);
        } else {
        	if (identifier != null && currentScope != null) {
                Symbol symbol = currentScope.getSymbol(identifier.getTokenOriginalValue());
                if (symbol != null) {
                    symbol.addUsage(identifier);
                }
            }
        }
    }
```

and added two tests:

```
  cursor c_x is select 'a' a from dual;
  t_x c_x%rowtype;  -- Noncompliant {{Remove this unused "t_x" local variable.}}
....
-- correct
  cursor c_x is select 'a' a from dual;
  r_x c_x%rowtype;
...
  for r_x in c_x
  loop
  	null;
  end loop;
```

**Comment by felipebz** [comment]
Hi @jleendertse.

The current behavior is correct. The variable `r_x` in your example **is not** being used.

See the ["Cursor FOR LOOP Statement" documentation](https://docs.oracle.com/en/database/oracle/oracle-database/18/lnpls/cursor-FOR-LOOP-statement.html#GUID-62C9A3C8-82F9-468F-8D84-81672E67736D). The cursor FOR LOOP is defined as `FOR record IN (...)`, where:

> **record**
> Name for the loop index that the cursor `FOR LOOP statement` **implicitly declares** as a `%ROWTYPE` record variable of the type that cursor or select_statement returns. [emphasis added]

Therefore, in your example you have a `r_x` variable that is never used and a `r_x` variable accessible only inside the cursor FOR LOOP that hides the outer `r_x`.

We can check this behavior with this code:

```
declare
  cursor c_x is select 'a' a from dual;
  r_x c_x%rowtype;
  
  procedure print_value is
  begin
    dbms_output.put_line('print_value: '||r_x.a);
  end;
begin
  r_x.a := 'x';
  for r_x in c_x loop
    dbms_output.put_line('inside loop: '||r_x.a);
    print_value;
  end loop;
end;
```

Here we're showing the value of `r_x.a` in two locations. If outer `r_x` is being used by the cursor FOR LOOP, these two put_line calls should print the same value, right?

But actually the output is

```
inside loop: a
print_value: x
```

**Comment by jleendertse** [comment]
Hello Felipe,

you are right, it is not necessary to declare the rowtype variable in case of a for loop. So the behaviour is correct.
