### ISSUE TITLE
Rowtype variable should not have columns when inserting

### ISSUE THREAD

**Issue by jleendertse** [felipebz/sonar-plsql#84]
Having the following test program
`
declare
	p_rec_tab tab%rowtype;
  
begin
	p_rec_tab.col := 'a';
	insert into tab values p_rec_tab;
end;`
gives an error: "Specify the columns in this INSERT." Since the rowtype has the same layout as the table, no listing of the columns is necessary.

**Comment by felipebz** [comment]
Hi. This is already fixed in the current 2.3.0-SNAPSHOT (commit https://github.com/felipebz/sonar-plsql/commit/93951becf21f2c9b8bce86c02d0cda68b840c020).

**Comment by phermsdorf** [comment]
Please see #51 
seems to be fixed

**Comment by jleendertse** [comment]
This works, thanks.
