### ISSUE TITLE
Custom rule: where to place properties file?

### ISSUE THREAD

**Issue by jleendertse** [felipebz/sonar-plsql#86]
The custom example check ForbiddenDmlCheck uses the deprecated createViolation method. The new addIssue method uses property files. The resource can only be found when adding it to the plsqlopen.properties file, which is part of the standard distribution. Is it possible to have a properties file in the custom check project stucture?

**Comment by felipebz** [comment]
@jleendertse the `addIssue` method doesn't read any property files. In that example, we could just use `addIssue(table, "Replace this query by a function of the USER_WRAPPER package.");` 😃

**Comment by jleendertse** [comment]
ok, thanks for the response
