### ISSUE TITLE
Analysis with RegEx Rule fails on SonarQube 7.4 with latest version

### ISSUE THREAD

**Issue by phermsdorf** [felipebz/sonar-plsql#87]
Hi,

we are running SonarQube 7.4. After upgrading the sonar-plsql module from 2.1 to the latest 2.3-SNAPSHOT release we are facing the following error:

> at org.sonar.plsqlopen.checks.XPathCheck.query(XPathCheck.java:56)
> 	at org.sonar.plsqlopen.checks.XPathCheck.visitFile(XPathCheck.java:65)
> 	at org.sonar.plsqlopen.squid.PlSqlAstWalker.walk(PlSqlAstWalker.java:62)
> 	at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanMainFile(PlSqlAstScanner.java:128)
> 	at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanFile(PlSqlAstScanner.java:99)
> 	at org.sonar.plsqlopen.PlSqlSquidSensor.execute(PlSqlSquidSensor.java:101)
> 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:45)
> 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:88)
> 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:62)
> 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
> 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:164)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
> 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:319)
> 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:314)
> 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:288)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
> 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
> 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:82)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
> 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:131)
> 	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
> 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
> 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
> 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
> 	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
> 	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
> 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
> Caused by: java.lang.RuntimeException: org.jaxen.JaxenException: org.jaxen.saxpath.base.XPathReader
> 	at com.sonar.sslr.xpath.api.AstNodeXPathQuery.<init>(AstNodeXPathQuery.java:38)
> 	at com.sonar.sslr.xpath.api.AstNodeXPathQuery.create(AstNodeXPathQuery.java:102)
> 	at org.sonar.plsqlopen.checks.XPathCheck.query(XPathCheck.java:54)
> 	... 36 more
> Caused by: org.jaxen.JaxenException: org.jaxen.saxpath.base.XPathReader
> 	at org.jaxen.BaseXPath.<init>(BaseXPath.java:125)
> 	at org.jaxen.BaseXPath.<init>(BaseXPath.java:142)
> 	at com.sonar.sslr.xpath.api.AstNodeXPathQuery.<init>(AstNodeXPathQuery.java:36)
> 	... 38 more
> Caused by: org.jaxen.saxpath.SAXPathException: org.jaxen.saxpath.base.XPathReader
> 	at org.jaxen.saxpath.helpers.XPathReaderFactory.createReader(XPathReaderFactory.java:152)
> 	at org.jaxen.saxpath.helpers.XPathReaderFactory.createReader(XPathReaderFactory.java:110)
> 	at org.jaxen.BaseXPath.<init>(BaseXPath.java:113)
> 	... 40 more
> Caused by: java.lang.ClassNotFoundException: org.jaxen.saxpath.base.XPathReader
> 	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
> 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
> 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at org.jaxen.saxpath.helpers.XPathReaderFactory.createReader(XPathReaderFactory.java:137)
> 	... 42 more

Thanks for looking at the issue.

Bye Peter

**Comment by felipebz** [comment]
Thanks, @phermsdorf. Sorry about that, it should be fixed now. Could you please test [this version](https://ci.appveyor.com/project/felipebz/sonar-plsql/builds/20134774/artifacts)?

**Comment by phermsdorf** [comment]
@felipebz  Works! Thanks!
