### ISSUE TITLE
sslr-plsql-toolkit-2.2.0.jar is not a plugin - error when running 7.4.0.18908

### ISSUE THREAD

**Issue by isgroup-srl** [felipebz/sonar-plsql#94]
If I download both JARs to plugins from the url https://github.com/felipebz/sonar-plsql/releases/tag/2.2.0 I get:

```
2018.12.13 14:27:49 ERROR web[][o.s.s.p.Platform] Web server startup failed: File is not a plugin. Please delete it and restart: /opt/sonarqube/extensions/plugins/sslr-plsql-toolkit-2.2.0.jar
```

**Comment by felipebz** [comment]
Hi.

You only need the sonar-plsql-open-plugin-2.2.0.jar. The sslr-plsql-toolkit is not a SonarQube plugin, it should not be put in the "plugins" directory. ;-)

**Comment by felipebz** [comment]
Sure! I updated the README and the release descriptions to be clearer about this (well... I tried). ;-)

Thank you for the feedback.
