### ISSUE TITLE
SonarLint support these rules?

### ISSUE THREAD

**Issue by HaroonRaizada** [felipebz/sonar-plsql#97]

**Comment by felipebz** [comment]
Hi @HaroonRaizada. No, it doesn't. SonarLint only supports the commercial plugin from SonarSource.

Are you using the SonarLint CLI or SonarLint for Eclipse/VSCode/etc?

I want to release some kind of command line tool and plugins for some IDEs to execute an analysis independently in the future. It would be very helpful if you could describe how do you use SonarLint. 😁

**Comment by HaroonRaizada** [comment]
Hi @felipebz . Thanks for the update!!
I am using SonarLint for Eclipse in connected Mode.  I am connecting SonarQube Server to Eclipse SonarLint. I was expecting that these rules will get reflected in SONARLINT as well.
Is there any workaround where i can achieve this functionality?

**Comment by felipebz** [comment]
No, there isn't any workaround for SonarLint. 😞 You'll have to execute a full analysis with SonarQube Scanner.

**Comment by HaroonRaizada** [comment]
Thanks For the Information:).
