### ISSUE TITLE
Can we parse Comments in the sql file?

### ISSUE THREAD

**Issue by HaroonRaizada** [felipebz/sonar-plsql#98]
--liquibase formatted sql

--changeset nvoxland:1
create table test1 (
    id int primary key,
    name varchar(255)
);
--rollback drop table test1;

Here in above sql file, can we analyze comments section?

**Comment by felipebz** [comment]
Hi @HaroonRaizada. Yes, you can.

Let's say that you want to create a [custom rule](https://github.com/felipebz/sonar-plsql/wiki/Create-a-plugin-with-custom-rules) to validate something in the comments. A minimal example would be:

```java
@Rule(name = "TODO", description = "TODO", key = "CommentCheck", priority = Priority.MAJOR)
@ConstantRemediation("10min")
public class CommentCheck extends PlSqlCheck {

    private PlSqlCommentAnalyzer commentAnalyzer = new PlSqlCommentAnalyzer();

    @Override
    public void visitToken(Token token) {
        for (Trivia trivia : token.getTrivia()) {
            String comment = commentAnalyzer.getContents(trivia.getToken().getOriginalValue());

            // check whatever you want and then...
            addIssue(trivia.getToken(), "test");
        }
    }
}
```

Using this you'll get the values "liquibase formatted sql", "changeset nvoxland:1" and "rollback drop table test1;" in the  `comment` variable.

**Comment by HaroonRaizada** [comment]
Thanks @felipebz :).This approach works fine.
